# Generated by Django 2.0.3 on 2018-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliatedstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('receipt_staff', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('affiliated_store', models.CharField(max_length=40)),
                ('item_number', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=20)),
                ('receipt_contents', models.TextField()),
                ('answer_staff', models.CharField(max_length=20)),
                ('answer_contents', models.TextField()),
                ('answer_date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('receipt_staff', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('supervisor', models.CharField(max_length=40)),
                ('affiliated_store', models.CharField(max_length=40)),
                ('receipt_channel', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=20)),
                ('receipt_contents', models.TextField()),
                ('answer_staff', models.CharField(max_length=20)),
                ('answer_contents', models.TextField()),
                ('answer_date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_code', models.CharField(max_length=50)),
                ('sunday', models.CharField(max_length=6)),
                ('monday', models.CharField(max_length=6)),
                ('tuesday', models.CharField(max_length=6)),
                ('wednesday', models.CharField(max_length=6)),
                ('thursday', models.CharField(max_length=6)),
                ('friday', models.CharField(max_length=6)),
                ('saturday', models.CharField(max_length=6)),
                ('center', models.CharField(max_length=20)),
            ],
        ),
    ]
